version: 0.2

env:
  variables:
    REPO_NAME:            "cookie-shop-serverless"
  parameter-store:
    SAM_S3_BUCKET:        "/build/SAM_S3_BUCKET"

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip3 install -q boto3 aws-sam-cli coverage aws-dynamodb-parser

  pre_build:
    commands:
      - aws cloudformation validate-template --template-body file://template.yaml
      - coverage run --branch --source='.' -m unittest
      - coverage report -m --fail-under=100 --omit=*/__init__.py,tests/*,cookie-shop-env/*

  build:
    commands:
      - aws s3 cp swagger.yaml s3://$SAM_S3_BUCKET
      - sam build -s src
      - sam package --s3-bucket $SAM_S3_BUCKET --output-template-file NewSamTemplate.yaml
      - sam deploy --s3-bucket $SAM_S3_BUCKET --no-fail-on-empty-changeset --capabilities CAPABILITY_NAMED_IAM --template-file NewSamTemplate.yaml --stack-name ${REPO_NAME}-stack --parameter-overrides S3Bucket=$SAM_S3_BUCKET
