version: 0.2

env:
  parameter-store:
    SERVICE_NAME:   "SERVICE_NAME"
    SAM_S3_BUCKET:  "SAM_S3_BUCKET"
    GITHUB_OWNER:   "GITHUB_OWNER"
    GITHUB_REPO:    "GITHUB_REPO"
    GITHUB_TOKEN:   "GITHUB_TOKEN"

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip3 install -q boto3 aws-sam-cli aws-dynamodb-parser

  build:
    commands:
      - aws s3 cp swagger.yaml s3://$SAM_S3_BUCKET/stg/
      - sam build -s src
      - sam package --s3-bucket $SAM_S3_BUCKET --s3-prefix stg --output-template-file NewSamTemplate.yaml
      - sam deploy --s3-bucket $SAM_S3_BUCKET --s3-prefix stg --no-fail-on-empty-changeset --capabilities CAPABILITY_NAMED_IAM --template-file NewSamTemplate.yaml --stack-name $SERVICE_NAME-stack --parameter-overrides ServiceName=$SERVICE_NAME S3Bucket=$SAM_S3_BUCKET/stg
