version: 0.2

env:
  parameter-store:
    SERVICE_NAME:   "SERVICE_NAME"
    SAM_S3_BUCKET:  "SAM_S3_BUCKET"
    GITHUB_OWNER:   "GITHUB_OWNER"
    GITHUB_REPO:    "GITHUB_REPO"
    GITHUB_TOKEN:   "GITHUB_TOKEN"

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install -q boto3 coverage aws-dynamodb-parser

  pre_build:
    commands:
      - aws cloudformation validate-template --template-body file://template.yaml
      - coverage run --branch --source='.' -m unittest
      - coverage report -m --fail-under=100 --omit=*/__init__.py,tests/*,cookie-shop-env/*

  build:
    commands:
      - export CLEAN_PR=$(echo $CODEBUILD_SOURCE_VERSION | tr '/' '-')
      - aws s3 cp swagger.yaml s3://$SAM_S3_BUCKET/dev/$CLEAN_PR/
      - sam build
      - sam package --s3-bucket $SAM_S3_BUCKET --s3-prefix dev/$CLEAN_PR --output-template-file NewSamTemplate.yaml
      - sam deploy --s3-bucket $SAM_S3_BUCKET --no-fail-on-empty-changeset --capabilities CAPABILITY_NAMED_IAM --template-file NewSamTemplate.yaml --stack-name $SERVICE_NAME-stack-$CLEAN_PR --s3-prefix dev/$CLEAN_PR --parameter-overrides ServiceName=$SERVICE_NAME ApiNameSuffix=$CLEAN_PR S3Bucket=$SAM_S3_BUCKET/dev/$CLEAN_PR
